Update symfony-ci.yml

diff --git a/.github/workflows/symfony-ci.yml b/.github/workflows/symfony-ci.yml
--- a/.github/workflows/symfony-ci.yml
+++ b/.github/workflows/symfony-ci.yml
@@ -43,9 +43,16 @@ jobs:
 
       - name: Install Docker Compose
         run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/2.19.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+          DOCKER_COMPOSE_VERSION=2.19.1
+          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
+          # Verify if the download was successful by checking the file size
+          if [[ ! -s /usr/local/bin/docker-compose ]]; then
+            echo "Docker Compose download failed!"
+            exit 1
+          fi
           docker-compose --version  # Verify Docker Compose installation
+
 
       - name: Set up Docker Compose
         run: | 
